[project]
name = "lockfile-resolver"
version = "0.1.0"
description = ""
authors = [
    {name = "Lubomír Sedlář", email = "lsedlar@redhat.com"},
]
readme = "README.md"

[tool.setuptools]
packages = ['lockfile_resolver']

[project.scripts]
lockfile-resolver = "lockfile_resolver:main"


[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project.entry-points."lockfile_resolver.content_origins"]
repos = "lockfile_resolver.content_origin.repos:RepoOrigin"
repofiles = "lockfile_resolver.content_origin.repofiles:RepofileOrigin"
composes = "lockfile_resolver.content_origin.composes:ComposeOrigin"
